name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

env:
  CGO_ENABLED: 0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Build for multiple platforms
        run: |
          # Get version from tag (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/}
          
          # Create directories for each platform
          mkdir -p linux-amd64 linux-arm64 darwin-amd64 darwin-arm64 windows-amd64 windows-arm64
          
          # Build for multiple platforms
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o linux-amd64/jumphost .
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o linux-arm64/jumphost .
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o darwin-amd64/jumphost .
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o darwin-arm64/jumphost .
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o windows-amd64/jumphost.exe .
          GOOS=windows GOARCH=arm64 go build -ldflags="-s -w" -o windows-arm64/jumphost.exe .
          
          # Create checksums
          find . -name "jumphost*" -type f -exec sha256sum {} \; > checksums.txt
          
          # Copy files to root for upload
          cp linux-amd64/jumphost ./jumphost-linux-amd64
          cp linux-arm64/jumphost ./jumphost-linux-arm64
          cp darwin-amd64/jumphost ./jumphost-darwin-amd64
          cp darwin-arm64/jumphost ./jumphost-darwin-arm64
          cp windows-amd64/jumphost.exe ./jumphost-windows-amd64.exe
          cp windows-arm64/jumphost.exe ./jumphost-windows-arm64.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            jumphost-linux-amd64
            jumphost-linux-arm64
            jumphost-darwin-amd64
            jumphost-darwin-arm64
            jumphost-windows-amd64.exe
            jumphost-windows-arm64.exe
            checksums.txt
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 